<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>TwelveDaParser</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ara3D.Parakeet" />
    <PackageReference Include="Ara3D.Parakeet.Grammars" />
    <PackageReference Include="Ara3D.Utils" />
  </ItemGroup>

</Project>
